codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        enabled: yes
        target: auto
        threshold: 5
    patch:
      default:
        enabled: yes
        target: auto
        threshold: 5
    changes: no